### ISSUE TITLE
Forget password button to text

### ISSUE THREAD

**Issue by smitbarmase** [DSC-VIT-BHOPAL/VITBOOK#2]
inside link https://vitbook.herokuapp.com/accounts/login/,
Reset password link button should be replaced with within the text "forget your password?".

**Comment by amycruz97** [comment]
can you elaborate more i can help resolve it for hacktoberfest

**Comment by charchithere** [comment]
Hello! I would like to work on this.

**Comment by hsrambo07** [comment]
Hey, i would like to contribute to this issue.

**Comment by smitbarmase** [comment]
Resolved. #13
