### ISSUE TITLE
Site is not responsive in mobile view

### ISSUE THREAD

**Issue by nikhilshukla07** [DSC-VIT-BHOPAL/VITBOOK#22]
![Screenshot_2020-10-02-18-29-18-84](https://user-images.githubusercontent.com/46022462/94925665-3b0e2b80-04dd-11eb-96a5-f474cfe1efd3.jpg)

**Comment by smitbarmase** [comment]
I fixed the welcome page for desktop as well as mobile optimized.
Take a look here: #25

**Comment by smitbarmase** [comment]
The issue has been resolved #25 and merged.
