### ISSUE TITLE
Side navbar icons need to be moved to left side of the text

### ISSUE THREAD

**Issue by smitbarmase** [DSC-VIT-BHOPAL/VITBOOK#7]
As you can see, the icons in the side navbar are not symmetrically aligned. So these need to be moved to the left side and the text on these buttons should come on the right, after the icon.
![Screenshot 2020-09-29 231308](https://user-images.githubusercontent.com/53087550/94596639-07978b00-02aa-11eb-9d80-7a4e70c4e28d.jpg)
">

**Comment by yesidays** [comment]
Hello, Can I work this?

**Comment by charchithere** [comment]
Hello! I would Like to Work on this Issue

**Comment by vikhyatsingh123** [comment]
Hey @smitbarmase, I am working on your issue and will soon complete it.
Assign me for this task.

**Comment by GunjanRajTiwari** [comment]
Gunjan from VIT Vellore. Can you assign me this task?

**Comment by GunjanRajTiwari** [comment]
#15 
Solved

**Comment by smitbarmase** [comment]
Resolved. #16
